### PR TITLE
Fix keyboard shortcut and rename extension

### PR DESCRIPTION
**Pull request by fturcheti**
Olá, Giovanni.

Now I have:

- Changed the keyboard shortcut to `Alt+P`
- Added a new "addon icon" – the icon the is used in the Add-ons Preferences, that should be used in the Firefox Add-ons website, etc.
- Refined the toolbar icons – just unnoticeable details
- Added a README.me file to the project
- And changed the extension name! – I'm joking... no, it's serious... I explain it below.

I'm proposing a change in the name of the extension: instead of just "Pinboard", I changed it to "Pinboard Button". This makes the extension distinguishable among other Pinboard ones in the Add-ons website, and better reflect the extension interface: it's more a button with a dropdown menu than a popup. The Pinboard extensions that refer to popups, commonly refer to popup windows, then it's a bit confusing using popup in the name and description of this extension.

You can publish the changes if you think this is OK. Also, I'd like to suggest you to change the icon and description of the extension in the official Add-ons website. You can use the new addon icon and the README content.

Saudações,
Felipe.

### CODE REVIEW

**Comment by fturcheti** [comment]
Another name that would fit is "Pinboard Menu". I'm not sure, but maybe it's better than "Pinboard Button".

**Comment by fiatjaf** [comment]
I first used "Pinboard Popup" because I wanted the "Save to Pinboard" button to open a real popup window to the `pinboard.in/add` URL. I however struggled against Firefox strange behavior of blocking all popups by default, even popups opened directly on `click` events and by extensions the user has himself installed, so I resorted to using the `tabs.create` method.

Apparently there is already an extension named "Pinboard Popup" that does basically the same thing as this one -- and you've contributed to it! -- so my question is: why do you prefer this one over that?

Maybe the name could reflect the fact that the extension doesn't use API keys or tries to reimplement the Pinboard interface, like almost all others. What do you think?

Anyway, "Pinboard Button" is good enough. `Alt+P` is great. I'll publish this one and then we can discuss more.

**Comment by fturcheti** [comment]
As I wrote in the first pull request, I keep going back to the Addons website looking for a simple and functional Pinboard extension. I think I have tried all of them. Before the advent of web-extensions, I was using the official addon – although it hasn't be updated in a long time, I never had problems with it. But now that this old model of extensions is dying, I had begun a search for replacements and haven't found everything I need yet.

To replace the official Pinboard extension, lately I was using that one named "Pinboard Popup" and it provides what I need: a simple shortcut to save bookmarks to Pinboard. But then I found that bug. I realized I could easily fix it, but the author did not answer the pull request, so I decided to make another visit to the Addons website and ended up finding yours as an alternative.

I like the idea of not having to deal with API keys and this simple menu you've came up with is a good addition to this simple formula – straightforward both in the UI/UX and in the code implementation. But for my user case a keyboard shortcut is a must. As a knew this was easy to implement, by previously reading the code of the other addon, I decided to add this functionality. And being a designer I like to have beautiful icons in my eyesight, then I felt an impulse to improve the graphic assets too.

That's the story!

**Comment by fturcheti** [comment]
I saw that you already published the changes to the Addons website. That's great! 

I'd just like to point an error in the "small description", the one highlighted under the the extension name:

> A very minimal Google Chrome Extention for Pinboard (http://pinboard.in) that doesn't use API keys, but just opens Pinboard windows.

It says "Google Chrome" instead of "Firefox". The same error is present at the description of this Github repository too.

**Comment by fiatjaf** [comment]
Oops.

**Pull request merged**
